version: "3.8"
services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app/uploads:/app/uploads 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:6-alpine

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formai
    ports:
      - "5432:5432"
